name: build
on:
  push:
  workflow_dispatch:

jobs:
  build-on-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        mode:
          - { full: Debug,          short: debug }
          - { full: RelWithDebInfo, short: fat   }
          - { full: MinSizeRel,     short: slim  }

    name: Build with ${{ matrix.mode.full }} on Ubuntu x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          mkdir -p /tmp/upd
          cd /tmp/upd
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode.full }} ${{ github.workspace }}
          make -j VERBOSE=1

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: bin-elf-x86_64-${{ matrix.mode.short }}
          path: /tmp/upd/upd
          if-no-files-found: ignore

  build-on-win64:
    strategy:
      fail-fast: false
      matrix:
        mode:
          - { full: RelWithDebInfo, short: fat   }
          - { full: MinSizeRel,     short: slim  }

    name: Build with ${{ matrix.mode.full }} on Win64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1

      - name: building
        run: |
          mkdir -p /tmp/upd
          cd /tmp/upd
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.mode.full }} ${{ github.workspace }}
          cmake --build . --verbose

      - name: 'uploading artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: upd-coff-x86_64-${{ matrix.mode.short }}
          path: /tmp/upd/upd.exe
          if-no-files-found: ignore

