name: build
on:
  push:
  workflow_dispatch:

jobs:
  build-on-ubuntu:
    name: 'Build on Ubuntu x86_64'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: 'building upd (Debug)'
        run: |
          mkdir -p /tmp/upd/Debug
          cd /tmp/upd/Debug
          cmake -DCMAKE_BUILD_TYPE=Debug ${{ github.workspace }}
          make -j VERBOSE=1

      - name: 'building upd (RelWithDebInfo)'
        run: |
          mkdir -p /tmp/upd/RelWithDebInfo
          cd /tmp/upd/RelWithDebInfo
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${{ github.workspace }}
          make -j VERBOSE=1

      - name: 'building upd (MinSizeRel)'
        run: |
          mkdir -p /tmp/upd/MinSizeRel
          cd /tmp/upd/MinSizeRel
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel ${{ github.workspace }}
          make -j VERBOSE=1

      - name: 'uploading artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: bin-elf-x86_64
          path: |
            /tmp/upd/Debug/upd
            /tmp/upd/Debug/updtest
            /tmp/upd/RelWithDebInfo/upd
            /tmp/upd/MinSizeRel/upd
          if-no-files-found: ignore

  build-on-msys2:
    name: 'Build on Win64'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1

      - name: 'building upd (Debug)'
        run: |
          mkdir -p /tmp/upd/Debug
          cd /tmp/upd/Debug
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug ${{ github.workspace }}
          cmake --build . --verbose

      - name: 'building upd (RelWithDebInfo)'
        run: |
          mkdir -p /tmp/upd/RelWithDebInfo
          cd /tmp/upd/RelWithDebInfo
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo ${{ github.workspace }}
          cmake --build . --verbose

      - name: 'building upd (MinSizeRel)'
        run: |
          mkdir -p /tmp/upd/MinSizeRel
          cd /tmp/upd/MinSizeRel
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=MinSizeRel ${{ github.workspace }}
          cmake --build . --verbose

      - name: 'uploading artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: bin-coff-x86_64
          path: |
            /tmp/upd/Debug/upd.exe
            /tmp/upd/Debug/updtest.exe
            /tmp/upd/Debug/lua51.dll
            /tmp/upd/RelWithDebInfo/upd.exe
            /tmp/upd/MinSizeRel/upd.exe
          if-no-files-found: ignore

